version: "3.9"

services:
  # ----------------------- FRONTEND -----------------------
  frontend:
    build: ./front
    container_name: vue-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:8001
      VITE_IMAGES_URL: http://localhost:8001

  # ----------------------- BACKEND -----------------------
  backend:
    build: ./back
    container_name: fastapi-backend
    restart: always
    ports:
      - "8001:8000"
    environment:
      # База данных и аутентификация
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/appdb
      JWT_SECRET: "supersecretkey123"
      JWT_ALG: "HS256"  # Изменил с JWT_ALGORITHM на JWT_ALG
      
      # Настройки изображений
      # BASE_URL: http://localhost:8001  # Для доступа с хоста
      # # BASE_URL: http://backend:8000  # Альтернатива для внутренней сети
      POSTERS_PATH: /app/posters
      POSTERS_BASE_URL: http://localhost:8001/posters
      
      # ML сервис
      ML_URL: http://movie-recommender:8000
    volumes:
      # Монтируем папку с постерами
      - ./back/posters:/app/posters:ro  # read-only для безопасности
    depends_on:
      - db
      - movie-recommender

  # ----------------------- ML SERVICE -----------------------
  movie-recommender:
    build: ./ml
    container_name: movie-recommender-api
    ports:
      - "8002:8000"
    volumes:
      - ./ml/data:/app/data:ro
      - ./ml/logs:/app/logs
    env_file:
      - ./ml/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ----------------------- POSTGRES -----------------------
  db:
    image: postgres:18
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./back/db_init:/docker-entrypoint-initdb.d

volumes:
  pgdata: